### ISSUE TITLE
Create employee ID as per the template {EXXXXXX} from backend while creating user.

### ISSUE THREAD

**Issue by ShubhamShete24** [ShubhamShete24/LeaveManagement#18]
Create collection `counter` for maintaining a count in **increasing order only**.
Generate EmployeeID based on the highest count from the collection `counter`. It should be like EXXXXXX.

**Comment by Arunangshu37** [comment]
@ShubhamShete24 anything remaining from my side to get this PR complete? Is there any dependency or blockage for this PR that I am unable to figure out at the moment?
